Profile: DeviceRequest314e
Parent: http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-devicerequest
Id: devicerequest-314e
Title: "314e DeviceRequest"
Description: """
314e-constrained DeviceRequest profile derived from QI-Core DeviceRequest.

This profile applies 314e-defined extensions and uses 314e datatype profiles
where applicable.
"""

* ^url = "http://314e.com/fhir/StructureDefinition/devicerequest-314e"
* ^status = #active

// ======================================================
// 314e EXTENSIONS
// ======================================================

* extension contains
    ResourceAdditionalInfo named additionalInfo 0..*

* extension[additionalInfo] ^short =
    "Supplementary information for this resource"

// ======================================================
// 314e DATATYPE CONSTRAINTS
// ======================================================

* identifier only Identifier314e
* basedOn only Reference314e
* basedOn ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/devicerequest-314e"
* basedOn ^type.targetProfile[1] = "http://314e.com/fhir/StructureDefinition/account-314e"
* basedOn ^type.targetProfile[2] = "http://314e.com/fhir/StructureDefinition/allergyintolerance-314e"
* basedOn ^type.targetProfile[3] = "http://314e.com/fhir/StructureDefinition/appointment-314e"
* basedOn ^type.targetProfile[4] = "http://314e.com/fhir/StructureDefinition/careplan-314e"
* basedOn ^type.targetProfile[5] = "http://314e.com/fhir/StructureDefinition/careteam-314e"
* basedOn ^type.targetProfile[6] = "http://314e.com/fhir/StructureDefinition/clinicalimpression-314e"
* basedOn ^type.targetProfile[7] = "http://314e.com/fhir/StructureDefinition/communicationrequest-314e"
* basedOn ^type.targetProfile[8] = "http://314e.com/fhir/StructureDefinition/condition-314e"
* basedOn ^type.targetProfile[9] = "http://314e.com/fhir/StructureDefinition/condition-diagnosis-314e"
* basedOn ^type.targetProfile[10] = "http://314e.com/fhir/StructureDefinition/condition-problem-healthconcern-314e"
* basedOn ^type.targetProfile[11] = "http://314e.com/fhir/StructureDefinition/contract-314e"
* basedOn ^type.targetProfile[12] = "http://314e.com/fhir/StructureDefinition/coverage-314e"
* basedOn ^type.targetProfile[13] = "http://314e.com/fhir/StructureDefinition/detectedissue-314e"
* basedOn ^type.targetProfile[14] = "http://314e.com/fhir/StructureDefinition/device-314e"
* basedOn ^type.targetProfile[15] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-314e"
* basedOn ^type.targetProfile[16] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-lab-314e"
* basedOn ^type.targetProfile[17] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-notereport-314e"
* basedOn ^type.targetProfile[18] = "http://314e.com/fhir/StructureDefinition/documentreference-314e"
* basedOn ^type.targetProfile[19] = "http://314e.com/fhir/StructureDefinition/encounter-314e"
* basedOn ^type.targetProfile[20] = "http://314e.com/fhir/StructureDefinition/endpoint-314e"
* basedOn ^type.targetProfile[21] = "http://314e.com/fhir/StructureDefinition/episodeofcare-314e"
* basedOn ^type.targetProfile[22] = "http://314e.com/fhir/StructureDefinition/goal-314e"
* basedOn ^type.targetProfile[23] = "http://314e.com/fhir/StructureDefinition/group-314e"
* basedOn ^type.targetProfile[24] = "http://314e.com/fhir/StructureDefinition/healthcareservice-314e"
* basedOn ^type.targetProfile[25] = "http://314e.com/fhir/StructureDefinition/imagingstudy-314e"
* basedOn ^type.targetProfile[26] = "http://314e.com/fhir/StructureDefinition/immunization-314e"
* basedOn ^type.targetProfile[27] = "http://314e.com/fhir/StructureDefinition/immunizationevaluation-314e"
* basedOn ^type.targetProfile[28] = "http://314e.com/fhir/StructureDefinition/immunizationrecommendation-314e"
* basedOn ^type.targetProfile[29] = "http://314e.com/fhir/StructureDefinition/location-314e"
* basedOn ^type.targetProfile[30] = "http://314e.com/fhir/StructureDefinition/media-314e"
* basedOn ^type.targetProfile[31] = "http://314e.com/fhir/StructureDefinition/medication-314e"
* basedOn ^type.targetProfile[32] = "http://314e.com/fhir/StructureDefinition/medicationadministration-314e"
* basedOn ^type.targetProfile[33] = "http://314e.com/fhir/StructureDefinition/medicationdispense-314e"
* basedOn ^type.targetProfile[34] = "http://314e.com/fhir/StructureDefinition/medicationrequest-314e"
* basedOn ^type.targetProfile[35] = "http://314e.com/fhir/StructureDefinition/molecularsequence-314e"
* basedOn ^type.targetProfile[36] = "http://314e.com/fhir/StructureDefinition/nutritionorder-314e"
* basedOn ^type.targetProfile[37] = "http://314e.com/fhir/StructureDefinition/observation-314e"
* basedOn ^type.targetProfile[38] = "http://314e.com/fhir/StructureDefinition/observation-antimicrobial-susceptibility-314e"
* basedOn ^type.targetProfile[39] = "http://314e.com/fhir/StructureDefinition/observation-lab-general-314e"
* basedOn ^type.targetProfile[40] = "http://314e.com/fhir/StructureDefinition/observation-microbiology-314e"
* basedOn ^type.targetProfile[41] = "http://314e.com/fhir/StructureDefinition/observation-microorganism-314e"
* basedOn ^type.targetProfile[42] = "http://314e.com/fhir/StructureDefinition/organization-314e"
* basedOn ^type.targetProfile[43] = "http://314e.com/fhir/StructureDefinition/patient-314e"
* basedOn ^type.targetProfile[44] = "http://314e.com/fhir/StructureDefinition/practitioner-314e"
* basedOn ^type.targetProfile[45] = "http://314e.com/fhir/StructureDefinition/practitionerrole-314e"
* basedOn ^type.targetProfile[46] = "http://314e.com/fhir/StructureDefinition/procedure-314e"
* basedOn ^type.targetProfile[47] = "http://314e.com/fhir/StructureDefinition/questionnaireresponse-314e"
* basedOn ^type.targetProfile[48] = "http://314e.com/fhir/StructureDefinition/relatedperson-314e"
* basedOn ^type.targetProfile[49] = "http://314e.com/fhir/StructureDefinition/requestgroup-314e"
* basedOn ^type.targetProfile[50] = "http://314e.com/fhir/StructureDefinition/schedule-314e"
* basedOn ^type.targetProfile[51] = "http://314e.com/fhir/StructureDefinition/servicerequest-314e"
* basedOn ^type.targetProfile[52] = "http://314e.com/fhir/StructureDefinition/slot-314e"
* basedOn ^type.targetProfile[53] = "http://314e.com/fhir/StructureDefinition/specimen-314e"
* basedOn ^type.targetProfile[54] = "http://314e.com/fhir/StructureDefinition/substance-314e"
* basedOn ^type.targetProfile[55] = "http://314e.com/fhir/StructureDefinition/task-314e"
* basedOn ^type.targetProfile[56] = "http://314e.com/fhir/StructureDefinition/visionprescription-314e"
* priorRequest only Reference314e
* priorRequest ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/devicerequest-314e"
* priorRequest ^type.targetProfile[1] = "http://314e.com/fhir/StructureDefinition/account-314e"
* priorRequest ^type.targetProfile[2] = "http://314e.com/fhir/StructureDefinition/allergyintolerance-314e"
* priorRequest ^type.targetProfile[3] = "http://314e.com/fhir/StructureDefinition/appointment-314e"
* priorRequest ^type.targetProfile[4] = "http://314e.com/fhir/StructureDefinition/careplan-314e"
* priorRequest ^type.targetProfile[5] = "http://314e.com/fhir/StructureDefinition/careteam-314e"
* priorRequest ^type.targetProfile[6] = "http://314e.com/fhir/StructureDefinition/clinicalimpression-314e"
* priorRequest ^type.targetProfile[7] = "http://314e.com/fhir/StructureDefinition/communicationrequest-314e"
* priorRequest ^type.targetProfile[8] = "http://314e.com/fhir/StructureDefinition/condition-314e"
* priorRequest ^type.targetProfile[9] = "http://314e.com/fhir/StructureDefinition/condition-diagnosis-314e"
* priorRequest ^type.targetProfile[10] = "http://314e.com/fhir/StructureDefinition/condition-problem-healthconcern-314e"
* priorRequest ^type.targetProfile[11] = "http://314e.com/fhir/StructureDefinition/contract-314e"
* priorRequest ^type.targetProfile[12] = "http://314e.com/fhir/StructureDefinition/coverage-314e"
* priorRequest ^type.targetProfile[13] = "http://314e.com/fhir/StructureDefinition/detectedissue-314e"
* priorRequest ^type.targetProfile[14] = "http://314e.com/fhir/StructureDefinition/device-314e"
* priorRequest ^type.targetProfile[15] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-314e"
* priorRequest ^type.targetProfile[16] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-lab-314e"
* priorRequest ^type.targetProfile[17] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-notereport-314e"
* priorRequest ^type.targetProfile[18] = "http://314e.com/fhir/StructureDefinition/documentreference-314e"
* priorRequest ^type.targetProfile[19] = "http://314e.com/fhir/StructureDefinition/encounter-314e"
* priorRequest ^type.targetProfile[20] = "http://314e.com/fhir/StructureDefinition/endpoint-314e"
* priorRequest ^type.targetProfile[21] = "http://314e.com/fhir/StructureDefinition/episodeofcare-314e"
* priorRequest ^type.targetProfile[22] = "http://314e.com/fhir/StructureDefinition/goal-314e"
* priorRequest ^type.targetProfile[23] = "http://314e.com/fhir/StructureDefinition/group-314e"
* priorRequest ^type.targetProfile[24] = "http://314e.com/fhir/StructureDefinition/healthcareservice-314e"
* priorRequest ^type.targetProfile[25] = "http://314e.com/fhir/StructureDefinition/imagingstudy-314e"
* priorRequest ^type.targetProfile[26] = "http://314e.com/fhir/StructureDefinition/immunization-314e"
* priorRequest ^type.targetProfile[27] = "http://314e.com/fhir/StructureDefinition/immunizationevaluation-314e"
* priorRequest ^type.targetProfile[28] = "http://314e.com/fhir/StructureDefinition/immunizationrecommendation-314e"
* priorRequest ^type.targetProfile[29] = "http://314e.com/fhir/StructureDefinition/location-314e"
* priorRequest ^type.targetProfile[30] = "http://314e.com/fhir/StructureDefinition/media-314e"
* priorRequest ^type.targetProfile[31] = "http://314e.com/fhir/StructureDefinition/medication-314e"
* priorRequest ^type.targetProfile[32] = "http://314e.com/fhir/StructureDefinition/medicationadministration-314e"
* priorRequest ^type.targetProfile[33] = "http://314e.com/fhir/StructureDefinition/medicationdispense-314e"
* priorRequest ^type.targetProfile[34] = "http://314e.com/fhir/StructureDefinition/medicationrequest-314e"
* priorRequest ^type.targetProfile[35] = "http://314e.com/fhir/StructureDefinition/molecularsequence-314e"
* priorRequest ^type.targetProfile[36] = "http://314e.com/fhir/StructureDefinition/nutritionorder-314e"
* priorRequest ^type.targetProfile[37] = "http://314e.com/fhir/StructureDefinition/observation-314e"
* priorRequest ^type.targetProfile[38] = "http://314e.com/fhir/StructureDefinition/observation-antimicrobial-susceptibility-314e"
* priorRequest ^type.targetProfile[39] = "http://314e.com/fhir/StructureDefinition/observation-lab-general-314e"
* priorRequest ^type.targetProfile[40] = "http://314e.com/fhir/StructureDefinition/observation-microbiology-314e"
* priorRequest ^type.targetProfile[41] = "http://314e.com/fhir/StructureDefinition/observation-microorganism-314e"
* priorRequest ^type.targetProfile[42] = "http://314e.com/fhir/StructureDefinition/organization-314e"
* priorRequest ^type.targetProfile[43] = "http://314e.com/fhir/StructureDefinition/patient-314e"
* priorRequest ^type.targetProfile[44] = "http://314e.com/fhir/StructureDefinition/practitioner-314e"
* priorRequest ^type.targetProfile[45] = "http://314e.com/fhir/StructureDefinition/practitionerrole-314e"
* priorRequest ^type.targetProfile[46] = "http://314e.com/fhir/StructureDefinition/procedure-314e"
* priorRequest ^type.targetProfile[47] = "http://314e.com/fhir/StructureDefinition/questionnaireresponse-314e"
* priorRequest ^type.targetProfile[48] = "http://314e.com/fhir/StructureDefinition/relatedperson-314e"
* priorRequest ^type.targetProfile[49] = "http://314e.com/fhir/StructureDefinition/requestgroup-314e"
* priorRequest ^type.targetProfile[50] = "http://314e.com/fhir/StructureDefinition/schedule-314e"
* priorRequest ^type.targetProfile[51] = "http://314e.com/fhir/StructureDefinition/servicerequest-314e"
* priorRequest ^type.targetProfile[52] = "http://314e.com/fhir/StructureDefinition/slot-314e"
* priorRequest ^type.targetProfile[53] = "http://314e.com/fhir/StructureDefinition/specimen-314e"
* priorRequest ^type.targetProfile[54] = "http://314e.com/fhir/StructureDefinition/substance-314e"
* priorRequest ^type.targetProfile[55] = "http://314e.com/fhir/StructureDefinition/task-314e"
* priorRequest ^type.targetProfile[56] = "http://314e.com/fhir/StructureDefinition/visionprescription-314e"
* groupIdentifier only Identifier314e
* code[x] only Reference314e or CodeableConcept314e
* code[x] ^type.targetProfile = "http://314e.com/fhir/StructureDefinition/device-314e"
* parameter.code only CodeableConcept314e
* subject only Reference314e
* subject ^type.targetProfile = "http://314e.com/fhir/StructureDefinition/patient-314e"
* encounter only Reference314e
* encounter ^type.targetProfile = "http://314e.com/fhir/StructureDefinition/encounter-314e"
* occurrence[x] only dateTime314e or Period314e or Timing314e
* authoredOn only dateTime314e
* requester only Reference314e
* requester ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/practitioner-314e"
* requester ^type.targetProfile[1] = "http://314e.com/fhir/StructureDefinition/practitionerrole-314e"
* requester ^type.targetProfile[2] = "http://314e.com/fhir/StructureDefinition/organization-314e"
* requester ^type.targetProfile[3] = "http://314e.com/fhir/StructureDefinition/device-314e"
* performerType only CodeableConcept314e
* performer only Reference314e
* performer ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/practitioner-314e"
* performer ^type.targetProfile[1] = "http://314e.com/fhir/StructureDefinition/practitionerrole-314e"
* performer ^type.targetProfile[2] = "http://314e.com/fhir/StructureDefinition/organization-314e"
* performer ^type.targetProfile[3] = "http://314e.com/fhir/StructureDefinition/careteam-314e"
* performer ^type.targetProfile[4] = "http://314e.com/fhir/StructureDefinition/healthcareservice-314e"
* performer ^type.targetProfile[5] = "http://314e.com/fhir/StructureDefinition/patient-314e"
* performer ^type.targetProfile[6] = "http://314e.com/fhir/StructureDefinition/device-314e"
* performer ^type.targetProfile[7] = "http://314e.com/fhir/StructureDefinition/relatedperson-314e"
* reasonCode only CodeableConcept314e
* reasonReference only Reference314e
* reasonReference ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/condition-314e"
* reasonReference ^type.targetProfile[1] = "http://314e.com/fhir/StructureDefinition/condition-diagnosis-314e"
* reasonReference ^type.targetProfile[2] = "http://314e.com/fhir/StructureDefinition/condition-problem-healthconcern-314e"
* reasonReference ^type.targetProfile[3] = "http://314e.com/fhir/StructureDefinition/observation-314e"
* reasonReference ^type.targetProfile[4] = "http://314e.com/fhir/StructureDefinition/observation-lab-general-314e"
* reasonReference ^type.targetProfile[5] = "http://314e.com/fhir/StructureDefinition/observation-microbiology-314e"
* reasonReference ^type.targetProfile[6] = "http://314e.com/fhir/StructureDefinition/observation-microorganism-314e"
* reasonReference ^type.targetProfile[7] = "http://314e.com/fhir/StructureDefinition/observation-antimicrobial-susceptibility-314e"
* reasonReference ^type.targetProfile[8] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-314e"
* reasonReference ^type.targetProfile[9] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-lab-314e"
* reasonReference ^type.targetProfile[10] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-notereport-314e"
* reasonReference ^type.targetProfile[11] = "http://314e.com/fhir/StructureDefinition/documentreference-314e"
* insurance only Reference314e
* insurance ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/coverage-314e"
* insurance ^type.targetProfile[1] = "http://hl7.org/fhir/StructureDefinition/ClaimResponse"
* supportingInfo only Reference314e
* supportingInfo ^type.targetProfile[0] = "http://314e.com/fhir/StructureDefinition/devicerequest-314e"
* supportingInfo ^type.targetProfile[1] = "http://314e.com/fhir/StructureDefinition/account-314e"
* supportingInfo ^type.targetProfile[2] = "http://314e.com/fhir/StructureDefinition/allergyintolerance-314e"
* supportingInfo ^type.targetProfile[3] = "http://314e.com/fhir/StructureDefinition/appointment-314e"
* supportingInfo ^type.targetProfile[4] = "http://314e.com/fhir/StructureDefinition/careplan-314e"
* supportingInfo ^type.targetProfile[5] = "http://314e.com/fhir/StructureDefinition/careteam-314e"
* supportingInfo ^type.targetProfile[6] = "http://314e.com/fhir/StructureDefinition/clinicalimpression-314e"
* supportingInfo ^type.targetProfile[7] = "http://314e.com/fhir/StructureDefinition/communicationrequest-314e"
* supportingInfo ^type.targetProfile[8] = "http://314e.com/fhir/StructureDefinition/condition-314e"
* supportingInfo ^type.targetProfile[9] = "http://314e.com/fhir/StructureDefinition/condition-diagnosis-314e"
* supportingInfo ^type.targetProfile[10] = "http://314e.com/fhir/StructureDefinition/condition-problem-healthconcern-314e"
* supportingInfo ^type.targetProfile[11] = "http://314e.com/fhir/StructureDefinition/contract-314e"
* supportingInfo ^type.targetProfile[12] = "http://314e.com/fhir/StructureDefinition/coverage-314e"
* supportingInfo ^type.targetProfile[13] = "http://314e.com/fhir/StructureDefinition/detectedissue-314e"
* supportingInfo ^type.targetProfile[14] = "http://314e.com/fhir/StructureDefinition/device-314e"
* supportingInfo ^type.targetProfile[15] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-314e"
* supportingInfo ^type.targetProfile[16] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-lab-314e"
* supportingInfo ^type.targetProfile[17] = "http://314e.com/fhir/StructureDefinition/diagnosticreport-notereport-314e"
* supportingInfo ^type.targetProfile[18] = "http://314e.com/fhir/StructureDefinition/documentreference-314e"
* supportingInfo ^type.targetProfile[19] = "http://314e.com/fhir/StructureDefinition/encounter-314e"
* supportingInfo ^type.targetProfile[20] = "http://314e.com/fhir/StructureDefinition/endpoint-314e"
* supportingInfo ^type.targetProfile[21] = "http://314e.com/fhir/StructureDefinition/episodeofcare-314e"
* supportingInfo ^type.targetProfile[22] = "http://314e.com/fhir/StructureDefinition/goal-314e"
* supportingInfo ^type.targetProfile[23] = "http://314e.com/fhir/StructureDefinition/group-314e"
* supportingInfo ^type.targetProfile[24] = "http://314e.com/fhir/StructureDefinition/healthcareservice-314e"
* supportingInfo ^type.targetProfile[25] = "http://314e.com/fhir/StructureDefinition/imagingstudy-314e"
* supportingInfo ^type.targetProfile[26] = "http://314e.com/fhir/StructureDefinition/immunization-314e"
* supportingInfo ^type.targetProfile[27] = "http://314e.com/fhir/StructureDefinition/immunizationevaluation-314e"
* supportingInfo ^type.targetProfile[28] = "http://314e.com/fhir/StructureDefinition/immunizationrecommendation-314e"
* supportingInfo ^type.targetProfile[29] = "http://314e.com/fhir/StructureDefinition/location-314e"
* supportingInfo ^type.targetProfile[30] = "http://314e.com/fhir/StructureDefinition/media-314e"
* supportingInfo ^type.targetProfile[31] = "http://314e.com/fhir/StructureDefinition/medication-314e"
* supportingInfo ^type.targetProfile[32] = "http://314e.com/fhir/StructureDefinition/medicationadministration-314e"
* supportingInfo ^type.targetProfile[33] = "http://314e.com/fhir/StructureDefinition/medicationdispense-314e"
* supportingInfo ^type.targetProfile[34] = "http://314e.com/fhir/StructureDefinition/medicationrequest-314e"
* supportingInfo ^type.targetProfile[35] = "http://314e.com/fhir/StructureDefinition/molecularsequence-314e"
* supportingInfo ^type.targetProfile[36] = "http://314e.com/fhir/StructureDefinition/nutritionorder-314e"
* supportingInfo ^type.targetProfile[37] = "http://314e.com/fhir/StructureDefinition/observation-314e"
* supportingInfo ^type.targetProfile[38] = "http://314e.com/fhir/StructureDefinition/observation-antimicrobial-susceptibility-314e"
* supportingInfo ^type.targetProfile[39] = "http://314e.com/fhir/StructureDefinition/observation-lab-general-314e"
* supportingInfo ^type.targetProfile[40] = "http://314e.com/fhir/StructureDefinition/observation-microbiology-314e"
* supportingInfo ^type.targetProfile[41] = "http://314e.com/fhir/StructureDefinition/observation-microorganism-314e"
* supportingInfo ^type.targetProfile[42] = "http://314e.com/fhir/StructureDefinition/organization-314e"
* supportingInfo ^type.targetProfile[43] = "http://314e.com/fhir/StructureDefinition/patient-314e"
* supportingInfo ^type.targetProfile[44] = "http://314e.com/fhir/StructureDefinition/practitioner-314e"
* supportingInfo ^type.targetProfile[45] = "http://314e.com/fhir/StructureDefinition/practitionerrole-314e"
* supportingInfo ^type.targetProfile[46] = "http://314e.com/fhir/StructureDefinition/procedure-314e"
* supportingInfo ^type.targetProfile[47] = "http://314e.com/fhir/StructureDefinition/questionnaireresponse-314e"
* supportingInfo ^type.targetProfile[48] = "http://314e.com/fhir/StructureDefinition/relatedperson-314e"
* supportingInfo ^type.targetProfile[49] = "http://314e.com/fhir/StructureDefinition/requestgroup-314e"
* supportingInfo ^type.targetProfile[50] = "http://314e.com/fhir/StructureDefinition/schedule-314e"
* supportingInfo ^type.targetProfile[51] = "http://314e.com/fhir/StructureDefinition/servicerequest-314e"
* supportingInfo ^type.targetProfile[52] = "http://314e.com/fhir/StructureDefinition/slot-314e"
* supportingInfo ^type.targetProfile[53] = "http://314e.com/fhir/StructureDefinition/specimen-314e"
* supportingInfo ^type.targetProfile[54] = "http://314e.com/fhir/StructureDefinition/substance-314e"
* supportingInfo ^type.targetProfile[55] = "http://314e.com/fhir/StructureDefinition/task-314e"
* supportingInfo ^type.targetProfile[56] = "http://314e.com/fhir/StructureDefinition/visionprescription-314e"
* note only Annotation314e
* relevantHistory only Reference314e
* relevantHistory ^type.targetProfile = "http://hl7.org/fhir/StructureDefinition/Provenance"
* meta only Meta314e
